global:
    scrape_interval: 10s 
    evaluation_interval: 10s

scrape_configs:
    - job_name: 'prometheus'
      static_configs:
      - targets: ['127.0.0.1:9090']

    - job_name: 'app-metrics'
      static_configs:
      - targets: ['127.0.0.1:4000']
      metrics_path: /metrics-text